### ISSUE TITLE
'name is wrong [113]'

### ISSUE THREAD

**Issue by sawan-flo** [niru-5/imusensor#7]
hello,
this is not particularly an error but when i initially run the kalman filter code, it 'prints' on the console <The name is wrong [113]> after which it takes about a second and then starts giving the roll,pitch,yaw value. Is it something to be concerned about? Also how to remove this message?

Thanks in advance

**Comment by niru-5** [comment]
Hi, 
That was a small check to make sure it gets connected to MPU9250. I kind of hardcoded it based on the few sensors. I don't think it should be a problem. 
I didn't put any verbose argument to mask the statement. I am not sure if I can get to it this week. You can open a pr for it, if you like. 

Thank You
Niru

**Comment by gitthnx** [comment]
`if (name[0] != 113 | name[0] != 115):`  instead of  `if not (name[0] == 113 | name[0] == 115):` avoids ID 'mismatch' information, e.g. "The name is wrong [115]"
